#!/usr/bin/env bash
# Concatenate core/*.md into AGENT_PROTOCOL.md.
# Run after editing anything in core/.
set -euo pipefail

cd "$(dirname "$0")/.."

out="AGENT_PROTOCOL.md"

{
  echo "# Agent Protocol"
  echo
  echo "A shared set of rules for coding agents across Claude Code, Cursor,"
  echo "GitHub Copilot, Windsurf, and any tool that reads \`AGENTS.md\`."
  echo
  echo "Generated from \`core/\`. Do not edit this file directly — edit the"
  echo "numbered source files in \`core/\` and re-run \`scripts/build.sh\`."
  echo
  for f in core/[0-9]*.md; do
    cat "$f"
    echo
  done
} > "$out"

echo "built $out from core/"
